---
title: "R Notebook"
output: html_notebook
---

Import the SBC:
```{r}
library(tidyverse)
library(here)
load(here("data", "sbc.Rdata"))
```

Get fixed unit length values:
```{r}
sbc = sbc %>% group_by(docId, unitId) %>% mutate(unitWordLen = sum(kind == "word")) %>% ungroup
```

Import mapper result:
```{r}
library(jsonlite)
mapper <- fromJSON(read_file(here("data/cluster_result/seed688/mapper_result_seed688_int2_ov0_1_eps0_35.json")))
```

word_info
```{r}
posterior_df <- read_csv(here("data/posterior_param_simple.csv"))
```


Code for producing staircases:
```{r}
get_avg_starfish <- function(words, node_id) {
  counts <- sbc %>%
    filter(text %in% words) %>%
    group_by(place, unitWordLen) %>%
    summarise(n = n(), .groups = "drop") %>%
    filter(unitWordLen < 20, !is.na(place), !is.na(unitWordLen))

  if (nrow(counts) == 0) return(NULL)

  g <- ggplot(counts, aes(place, unitWordLen)) +
    ggtitle(node_id) +
    ylab('IU length') +
    xlab('Place') +
    geom_tile(aes(fill = n), color='white') +
    scale_fill_gradient(low = 'white', high = 'darkblue') + #theme_grey() +
    theme(axis.text.x=element_text(),
          axis.ticks=element_line(),
          axis.line=element_blank(),
          panel.border=element_blank(),
          panel.grid.minor=element_line(color='#FFFFFF', linetype= 1, size = .5),
          panel.grid.major=element_blank(),
          legend.spacing.x = unit(7, 'mm')) +
    scale_y_continuous(breaks = 1:20, minor_breaks = seq(.5,20.5,1), limits = c(.5, 20)) +
    scale_x_continuous(breaks = 1:20, minor_breaks = seq(.5,20.5,1), limits = c(0.5, 20)) + geom_vline(xintercept = .5) + geom_hline(yintercept = .5) + geom_abline(intercept = -1, slope = 1)
  return(g)
}

# ---- loop over mapper nodes ----
plots <- list()

for (i in seq_along(mapper$points_in_vertex)) {
  node_points <- mapper$points_in_vertex[[i]]
  node_words <- posterior_df$word[node_points + 1]

  p <- get_avg_starfish(node_words, i)
  if (!is.null(p)) {
    plots[[i]] <- p
    ggsave(
      filename = sprintf("output/mapper_staircase/node_%02d_avg.png", i),
      plot = p,
      width = 6, height = 5, dpi = 300
    )
  }
}

plots[[19]]
```

```{r}

reversed <- posterior_df %>%
  filter((back == FALSE & hurdle_place < 0) | (back == TRUE & hurdle_place >= 0))

```



